#!/usr/bin/env node

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { auditRecordSchema, type AuditRecord } from "../audit/record";

export interface DigestResult {
  markdown: string;
  renderedCount: number;
  skippedCount: number;
  warnings: string[];
  nonBlocking: boolean;
}

export interface DigestOptions {
  auditDir?: string;
  outputPath?: string;
  limit?: number;
}

export async function renderDigestFromAuditDir(options: DigestOptions = {}): Promise<DigestResult> {
  const auditDir = options.auditDir ?? ".cache/audit";
  const outputPath = options.outputPath ?? "SECURITY-PATCHES.md";
  const limit = options.limit ?? 20;
  const warnings: string[] = [];
  const records: AuditRecord[] = [];

  let files: string[] = [];
  try {
    files = await readdir(auditDir);
  } catch (error) {
    if (isNotFound(error)) {
      const markdown = renderMarkdown([], 0);
      await writeOutput(outputPath, markdown);
      return {
        markdown,
        renderedCount: 0,
        skippedCount: 0,
        warnings,
        nonBlocking: true,
      };
    }
    warnings.push(`failed to read ${auditDir}: ${messageFor(error)}`);
  }

  for (const file of files.filter((candidate) => candidate.endsWith(".json"))) {
    const path = join(auditDir, file);
    try {
      records.push(auditRecordSchema.parse(JSON.parse(await readFile(path, "utf8"))));
    } catch (error) {
      warnings.push(`${file}: ${messageFor(error)}`);
    }
  }

  const sorted = records.sort((left, right) => right.createdAt.localeCompare(left.createdAt));
  const rendered = sorted.slice(0, limit);
  const olderCount = Math.max(0, sorted.length - rendered.length);
  const markdown = renderMarkdown(rendered, olderCount);
  await writeOutput(outputPath, markdown);

  return {
    markdown,
    renderedCount: rendered.length,
    skippedCount: warnings.length,
    warnings,
    nonBlocking: true,
  };
}

export async function main(argv = process.argv.slice(2)) {
  const parsed = parseArgs(argv);
  const result = await renderDigestFromAuditDir({
    auditDir: parsed.options.get("audit-dir") ?? ".cache/audit",
    outputPath: parsed.options.get("output") ?? "SECURITY-PATCHES.md",
    limit: Number(parsed.options.get("limit") ?? "20"),
  });
  for (const warning of result.warnings) {
    process.stderr.write(`digest warning: ${warning}\n`);
  }
  process.stdout.write(
    `sca digest completed: rendered=${result.renderedCount}, skipped=${result.skippedCount}, nonBlocking=true\n`,
  );
}

function renderMarkdown(records: AuditRecord[], olderCount: number) {
  const lines = [
    "# Security Patches",
    "",
    "<!-- Generated by `sca digest`; read-only projection of audit records. -->",
    "",
  ];

  if (records.length === 0) {
    lines.push("No remediations yet.", "");
    return lines.join("\n");
  }

  lines.push(
    "| Date | Advisory | Package | Version delta | Reviewer verdict | Outcome | Audit |",
    "|---|---|---|---|---|---|---|",
  );
  for (const record of records) {
    lines.push(
      [
        record.createdAt.slice(0, 10),
        redact(record.advisoryId),
        redact(record.packageName),
        `${redact(record.fromVersion)} -> ${redact(record.toVersion)}`,
        verdictFor(record),
        outcomeFor(record),
        redact(record.path),
      ]
        .join(" | ")
        .replace(/^/, "| ") + " |",
    );
  }
  if (olderCount > 0) {
    lines.push("", `${olderCount} older remediation(s) summarized by count only.`);
  }
  lines.push("");
  return lines.join("\n");
}

function verdictFor(record: AuditRecord) {
  return record.checks["release-reviewer-verdict"] === "success" ? "approve" : "unknown";
}

function outcomeFor(record: AuditRecord) {
  const required = [
    "build",
    "test",
    "sast",
    "fixtures-not-installed",
    "release-reviewer-verdict",
    "dependency-review",
  ];
  return required.every((check) => record.checks[check] === "success")
    ? "merged + released"
    : "not released";
}

async function writeOutput(path: string, markdown: string) {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, markdown);
}

function redact(value: string) {
  return value.replace(
    /(ghp_[A-Za-z0-9_]{20,}|github_pat_[A-Za-z0-9_]+|sk-[A-Za-z0-9]{16,}|xox[baprs]-[A-Za-z0-9-]{10,})/g,
    "[redacted-secret]",
  );
}

function messageFor(error: unknown) {
  return error instanceof Error ? error.message : String(error);
}

function isNotFound(error: unknown) {
  return (
    error instanceof Error && "code" in error && (error as NodeJS.ErrnoException).code === "ENOENT"
  );
}

function parseArgs(argv: string[]) {
  const command = argv[0] && !argv[0].startsWith("--") ? argv[0] : "";
  const rest = command === "digest" ? argv.slice(1) : argv;
  const options = new Map<string, string>();
  for (let index = 0; index < rest.length; index += 1) {
    const token = rest[index];
    if (token.startsWith("--")) {
      const [key, inlineValue] = token.slice(2).split("=", 2);
      const value = inlineValue ?? rest[index + 1];
      if (inlineValue === undefined) {
        index += 1;
      }
      if (!value) {
        throw new Error(`missing value for --${key}`);
      }
      options.set(key, value);
    }
  }
  return { command, options };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error: unknown) => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
